AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Capa 4: API de Consumo (Producción)"

Parameters:
  BucketName:
    Type: String
  ImageUri:
    Type: String

Resources:
  ComplianceApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Auth:
        ApiKeyRequired: true # Requerir API Key para que el Usage Plan tenga sentido

  ComplianceSearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Ref ImageUri
      MemorySize: 1024
      Timeout: 30
      Environment:
        Variables:
          COMPLIANCE_LAKE_BUCKET: !Ref BucketName
          GOLD_ZONE_PATH: !Sub s3://${BucketName}/gold/listas
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref BucketName
      Events:
        CheckNameApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
            RestApiId: !Ref ComplianceApi

  # Plan de Uso para controlar el consumo y habilitar API Keys
  ComplianceUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: ComplianceApi
    Properties:
      UsagePlanName: "ComplianceGuard-Standard-Plan"
      Description: "Plan de uso estándar para consulta de listas"
      ApiStages:
        - ApiId: !Ref ComplianceApi
          Stage: prod
      Throttle:
        BurstLimit: 10
        RateLimit: 5
      Quota:
        Limit: 1000
        Period: MONTH

Outputs:
  ApiUrl:
    Value: !Sub "https://${ComplianceApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
