AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Capa 4: API de Consumo (Producción) con UsagePlan nativo"

Parameters:
  BucketName:
    Type: String

Resources:
  ComplianceApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'OPTIONS,GET,POST'"
        AllowHeaders: "'Content-Type,X-Api-Key,Accept,Authorization'"
        AllowOrigin: "'*'"
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: "ComplianceGuard-Standard-Plan"
          Description: "Plan de uso estándar para consulta de listas"
          Quota:
            Limit: 1000
            Period: MONTH
          Throttle:
            BurstLimit: 10
            RateLimit: 5

  ComplianceSearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: reinesdev-compliance-api-func
      PackageType: Zip
      Runtime: python3.12
      CodeUri: ../../api-build/
      Handler: src.api.lambda_api.handler
      Layers:
        - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python312:14
      MemorySize: 1024
      Timeout: 30
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref BucketName
      Events:
        CheckNameApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
            RestApiId: !Ref ComplianceApi

  ComplianceSearchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ComplianceSearchFunction}"
      RetentionInDays: 7

Outputs:
  ApiUrl:
    Value: !Sub "https://${ComplianceApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
