AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Capa 1: Extractores (Lambdas) - Estructura Plana"

Parameters:
  BucketName:
    Type: String

Globals:
  Function:
    Timeout: 120
    MemorySize: 256
    Runtime: python3.12
    CodeUri: ../../extractors.zip
    Environment:
      Variables:
        COMPLIANCE_LAKE_BUCKET: !Ref BucketName
        LANDING_ZONE_PATH: !Sub s3://${BucketName}/landing/listas
        OFAC_SDN_URL: "https://www.treasury.gov/ofac/downloads/sdn.csv"
        OFAC_ALT_URL: "https://www.treasury.gov/ofac/downloads/add.csv"
        ONU_URL: "https://scsanctions.un.org/resources/xml/en/consolidated.xml"

Resources:
  ExtractOfacFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ofac_handler.ofac_handler
      CodeUri: ../../extractors.zip
      Policies:
        - S3CrudPolicy: { BucketName: !Ref BucketName }

  ExtractOnuFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: onu_handler.onu_handler
      CodeUri: ../../extractors.zip
      Policies:
        - S3CrudPolicy: { BucketName: !Ref BucketName }

  ExtractOpenSanctionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: opensanctions_handler.opensanctions_proxy_handler
      CodeUri: ../../extractors.zip
      Policies:
        - S3CrudPolicy: { BucketName: !Ref BucketName }

Outputs:
  ExtractOfacArn:
    Value: !GetAtt ExtractOfacFunction.Arn
  ExtractOnuArn:
    Value: !GetAtt ExtractOnuFunction.Arn
  ExtractOpenSanctionsArn:
    Value: !GetAtt ExtractOpenSanctionsFunction.Arn
