AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Capa 1: Extractores (Lambdas) - Estructura Plana"

Parameters:
  BucketName:
    Type: String
  DatosGovKeyId:
    Type: String
    NoEcho: true
  DatosGovApiKey:
    Type: String
    NoEcho: true

Globals:
  Function:
    Timeout: 120
    MemorySize: 256
    Runtime: python3.12
    CodeUri: ../../extractors.zip
    Environment:
      Variables:
        COMPLIANCE_LAKE_BUCKET: !Ref BucketName
        LANDING_ZONE_PATH: !Sub s3://${BucketName}/landing/listas
        OFAC_SDN_URL: "https://www.treasury.gov/ofac/downloads/sdn.csv"
        OFAC_ALT_URL: "https://www.treasury.gov/ofac/downloads/add.csv"
        SAT69B_URL: "http://omawww.sat.gob.mx/cifras_sat/Documents/ListadoGlobalDefinitivo.csv"
        ONU_URL: "https://scsanctions.un.org/resources/xml/en/consolidated.xml"
        PEP_URL: "https://www.datos.gov.co/api/v3/views/3qxn-uc22/query.json"
        DATOS_GOV_KEY_ID: "d6if00d6bulczelcxwh1ofa05"
        DATOS_GOV_API_KEY: "2we7eyfg1mz7xo1o0bwio1dmva730c4r0m1e958iiwxp60bl4m"

Resources:
  ExtractOfacFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ofac_handler.ofac_handler
      CodeUri: ../../extractors.zip
      Policies:
        - S3CrudPolicy: { BucketName: !Ref BucketName }

  ExtractOnuFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: onu_handler.onu_handler
      CodeUri: ../../extractors.zip
      Policies:
        - S3CrudPolicy: { BucketName: !Ref BucketName }

  ExtractSatFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: sat_handler.sat69b_handler
      CodeUri: ../../extractors.zip
      Policies:
        - S3CrudPolicy: { BucketName: !Ref BucketName }

  ExtractPepFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: pep_handler.socrata_pep_handler
      CodeUri: ../../extractors.zip
      Environment:
        Variables:
          DATOS_GOV_KEY_ID: !Ref DatosGovKeyId
          DATOS_GOV_API_KEY: !Ref DatosGovApiKey
      Policies:
        - S3CrudPolicy: { BucketName: !Ref BucketName }

  ExtractOpenSanctionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: opensanctions_handler.opensanctions_proxy_handler
      CodeUri: ../../extractors.zip
      Policies:
        - S3CrudPolicy: { BucketName: !Ref BucketName }

Outputs:
  ExtractOfacArn:
    Value: !GetAtt ExtractOfacFunction.Arn
  ExtractOnuArn:
    Value: !GetAtt ExtractOnuFunction.Arn
  ExtractSatArn:
    Value: !GetAtt ExtractSatFunction.Arn
  ExtractPepArn:
    Value: !GetAtt ExtractPepFunction.Arn
  ExtractOpenSanctionsArn:
    Value: !GetAtt ExtractOpenSanctionsFunction.Arn
