AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Capa 3: Orquestación (Step Functions)"

Parameters:
  OfacJob: { Type: String }
  OnuJob: { Type: String }
  OpenSanctionsJob: { Type: String }
  CrawlerName: { Type: String }
  ExtractOfacArn: { Type: String }
  ExtractOnuArn: { Type: String }
  ExtractOpenSanctionsArn: { Type: String }

Resources:
  ComplianceStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: reinesdev-compliance-sm-prd
      Events:
        BiweeklyTrigger:
          Type: Schedule
          Properties:
            Schedule: "cron(30 10 ? * WED,SUN *)"
            Name: ejecuta_step_function_api
            Description: "Ejecuta el ETL 2 veces por semana (Miercoles y Domingos) a las 05:30 AM Hora Local (10:30 UTC)."
            Enabled: true
      Definition:
        Comment: "Orquestador ELT modular (Nested)"
        StartAt: ParallelExtraction
        States:
          ParallelExtraction:
            Type: Parallel
            Next: RunCrawler
            Branches:
              - StartAt: ExtractOFAC
                States:
                  ExtractOFAC:
                    Type: Task
                    Resource: !Ref ExtractOfacArn
                    Parameters:
                      "OFAC_SDN_URL": "https://www.treasury.gov/ofac/downloads/sdn.csv"
                    Next: TransformOFAC
                  TransformOFAC:
                    Type: Task
                    Resource: arn:aws:states:::glue:startJobRun.sync
                    Parameters:
                      JobName: !Ref OfacJob
                      Arguments:
                        "--LANDING_ZONE_PATH": "s3://reinesdev-compliance-lake-prd/landing/listas"
                        "--GOLD_ZONE_PATH": "s3://reinesdev-compliance-lake-prd/gold/listas"
                    End: true
              - StartAt: ExtractONU
                States:
                  ExtractONU:
                    Type: Task
                    Resource: !Ref ExtractOnuArn
                    Parameters:
                      "ONU_URL": "https://scsanctions.un.org/resources/xml/en/consolidated.xml"
                    Next: TransformONU
                  TransformONU:
                    Type: Task
                    Resource: arn:aws:states:::glue:startJobRun.sync
                    Parameters:
                      JobName: !Ref OnuJob
                      Arguments:
                        "--LANDING_ZONE_PATH": "s3://reinesdev-compliance-lake-prd/landing/listas"
                        "--GOLD_ZONE_PATH": "s3://reinesdev-compliance-lake-prd/gold/listas"
                    End: true
              - StartAt: ExtractOpenSanctions
                States:
                  ExtractOpenSanctions:
                    Type: Task
                    Resource: !Ref ExtractOpenSanctionsArn
                    Parameters:
                      "source_id": "us_fbi_most_wanted"
                    Next: TransformOpenSanctions
                  TransformOpenSanctions:
                    Type: Task
                    Resource: arn:aws:states:::glue:startJobRun.sync
                    Parameters:
                      JobName: !Ref OpenSanctionsJob
                      Arguments:
                        "--OPENSANCTIONS_SOURCE_ID": "us_fbi_most_wanted"
                        "--LANDING_ZONE_PATH": "s3://reinesdev-compliance-lake-prd/landing/listas"
                        "--GOLD_ZONE_PATH": "s3://reinesdev-compliance-lake-prd/gold/listas"
                    End: true
          RunCrawler:
            Type: Task
            Resource: arn:aws:states:::aws-sdk:glue:startCrawler
            Parameters:
              Name: !Ref CrawlerName
            End: true
      Policies:
        - Statement:
            - Effect: Allow
              Action: ["lambda:InvokeFunction"]
              Resource: "*"
            - Effect: Allow
              Action:
                - glue:StartJobRun
                - glue:GetJobRun
                - glue:GetJobRuns
                - glue:BatchStopJobRun
                - glue:StartCrawler
                - glue:GetCrawler
              Resource: "*" 
