AWSTemplateFormatVersion: '2010-09-09'
Description: "ComplianceGuard - Root Stack (Pure CloudFormation Orchestrator)"

Parameters:
  FoundationStackName:
    Type: String
    Default: reinesdev-compliance-foundation
  ImageUri:
    Type: String
    Description: "URI de la imagen Docker para la API (ECR)"

Resources:
  # CAPA 1: EXTRACTORES
  ExtractorsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: nested/extractors.yaml
      Parameters:
        BucketName: !ImportValue 
          Fn::Sub: "${FoundationStackName}-BucketName"

  # CAPA 2: ETL (Depende de Capa 1)
  EtlStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: nested/etl.yaml
      Parameters:
        BucketName: !ImportValue 
          Fn::Sub: "${FoundationStackName}-BucketName"
        GlueRoleArn: !ImportValue
          Fn::Sub: "${FoundationStackName}-GlueRoleArn"
        DatabaseName: !ImportValue
          Fn::Sub: "${FoundationStackName}-GlueDatabaseName"

  # CAPA 3: ORQUESTACIÓN (Depende de Capa 1 y 2)
  OrchestratorStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: nested/orchestrator.yaml
      Parameters:
        OfacJob: !GetAtt EtlStack.Outputs.OfacGlueJobName
        OnuJob: !GetAtt EtlStack.Outputs.OnuGlueJobName
        SatJob: !GetAtt EtlStack.Outputs.SatGlueJobName
        PepJob: !GetAtt EtlStack.Outputs.PepGlueJobName
        OpenSanctionsJob: !GetAtt EtlStack.Outputs.OpenSanctionsGlueJobName
        CrawlerName: !GetAtt EtlStack.Outputs.ComplianceCrawlerName
        ExtractOfacArn: !GetAtt ExtractorsStack.Outputs.ExtractOfacArn
        ExtractOnuArn: !GetAtt ExtractorsStack.Outputs.ExtractOnuArn
        ExtractSatArn: !GetAtt ExtractorsStack.Outputs.ExtractSatArn
        ExtractPepArn: !GetAtt ExtractorsStack.Outputs.ExtractPepArn
        ExtractOpenSanctionsArn: !GetAtt ExtractorsStack.Outputs.ExtractOpenSanctionsArn

  # CAPA 4: API
  ApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: nested/api.yaml
      Parameters:
        BucketName: !ImportValue 
          Fn::Sub: "${FoundationStackName}-BucketName"
        ImageUri: !Ref ImageUri

Outputs:
  ApiEndpoint:
    Description: "URL base del API Gateway"
    Value: !GetAtt ApiStack.Outputs.ApiUrl
