FROM public.ecr.aws/lambda/python:3.12

# Instalar dependencias del sistema requeridas por DeltaLake/Pandas
RUN dnf update -y && \
    dnf install -y gcc-c++ make && \
    dnf clean all

# Copiar archivos de dependencias
COPY requirements.txt ./
COPY requirements-aws.txt ./

# Instalar dependencias de Python combinando Core + AWS (Actualizando PIP para suprimir warnings)
RUN pip install --upgrade pip --root-user-action=ignore && \
    pip install -r requirements.txt -r requirements-aws.txt --root-user-action=ignore

# Copiar el core aplicativo y los adaptadores al directorio Lambda /var/task
COPY src/ ${LAMBDA_TASK_ROOT}/src/
COPY cloud/ ${LAMBDA_TASK_ROOT}/cloud/

# CMD depends on the specific AWS SAM Template resource handler override
# Defaulting to API here just as fallback
CMD ["cloud.aws.lambda_api.handler"]
