import sys
import datetime
import re
from awsglue.transforms import *
from awsglue.utils import getResolvedOptions
from pyspark.context import SparkContext
from awsglue.context import GlueContext
from awsglue.job import Job
from pyspark.sql.functions import col, lit, current_date, udf, md5, concat_ws, date_format
from pyspark.sql.types import StringType

# 1. Job Initialization
args = getResolvedOptions(sys.argv, ['JOB_NAME', 'LANDING_ZONE_PATH', 'GOLD_ZONE_PATH', 'OPENSANCTIONS_SOURCE_ID'])
sc = SparkContext()
glueContext = GlueContext(sc)
spark = glueContext.spark_session
job = Job(glueContext)
job.init(args['JOB_NAME'], args)

landing_path = args.get('LANDING_ZONE_PATH')
gold_path = args.get('GOLD_ZONE_PATH')
source_id = args.get('OPENSANCTIONS_SOURCE_ID')

if not landing_path or not gold_path or not source_id:
    raise ValueError("LANDING_ZONE_PATH, GOLD_ZONE_PATH y OPENSANCTIONS_SOURCE_ID son obligatorios.")

today_str = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")

# Path resolves dynamically to the Step Function parameter payload (source_id)
os_landing_path = f"{landing_path}/opensanctions/{source_id}/fecha_carga={today_str}/entities.json"

logger = glueContext.get_logger()
logger.info(f"Reading raw OpenSanctions data for {source_id} from {os_landing_path}")

try:
    # 2. Extract Data (FTM JSON Line format from OpenSanctions)
    # OpenSanctions usually delivers NDJSON (Newline Delimited JSON)
    raw_df = spark.read.json(os_landing_path)

    def clean_string(name):
        if not name:
            return ""
        cleaned = re.sub(r'[^a-zA-Z0-9\s]', '', str(name))
        cleaned = re.sub(r'\s+', ' ', cleaned)
        return cleaned.strip().upper()

    clean_string_udf = udf(clean_string, StringType())

    # 3. Transform OpenSanctions Structure
    # Check schema for existing properties to avoid AnalysisException
    available_properties = []
    if "properties" in raw_df.schema.names:
        available_properties = raw_df.schema["properties"].dataType.names

    # Definir columnas dinámicas basadas en la existencia en el esquema
    notes_col = col("properties.notes").cast("string") if "notes" in available_properties else lit("")
    topics_col = col("properties.topics").cast("string") if "topics" in available_properties else lit("")
    name_col = col("properties.name")[0] if "name" in available_properties else lit("-")

    transformed_df = raw_df.select(
        md5(concat_ws("-", lit(source_id.upper()), col("id"))).alias("id_unico"),
        name_col.alias("nombre_original"),
        clean_string_udf(name_col).alias("nombre_limpio"),
        lit("-").alias("identificacion"),
        col("schema").alias("tipo_entidad"),
        lit("SANCIONES").alias("tipo_lista"),
        date_format(current_date(), "yyyy-MM-dd").alias("fecha_carga"),
        lit(source_id.upper()).alias("fuente"),
        concat_ws(" | Topics: ", topics_col, notes_col).alias("metadata")
    )

    transformed_df = transformed_df.fillna("-", subset=["identificacion", "tipo_entidad", "nombre_original", "nombre_limpio"])
    
    # Filter out empty names generated by schema artifacts
    transformed_df = transformed_df.filter(col("nombre_original") != "-")

    # 4. Load OpenSanctions Data to Gold Zone
    logger.info(f"Writing {source_id.upper()} Data to {gold_path} partitioned by fuente")
    transformed_df.write \
        .mode("append") \
        .partitionBy("fuente") \
        .parquet(f"{gold_path}/")

    logger.info(f"Glue OpenSanctions ETL Job completed successfully for {source_id}.")

except Exception as e:
    logger.error(f"Error processing OpenSanctions data for {source_id}: {str(e)}")
    raise e

job.commit()
